import { LegalPageShell, LegalSection, PlaceholderNotice } from '@/components/legal-page-shell';

export default function TermsPage() {
  return <LegalPageShell eyebrow="Nutzungsbedingungen" title="Allgemeine Geschäftsbedingungen" intro="Regeln für die Nutzung der RankedDarts-Plattform und der optionalen Premium-Mitgliedschaft.">
    <PlaceholderNotice />
    <LegalSection title="1. Geltungsbereich"><p>Diese Bedingungen regeln die Nutzung von RankedDarts zwischen dem Anbieter [Anbietername] und den Nutzern. Für einzelne Turniere gelten ergänzend die Turnierregeln sowie die jeweils auf der Turnierseite genannten Bedingungen.</p></LegalSection>
    <LegalSection title="2. Nutzerkonto"><p>Du bist für die Richtigkeit deiner Angaben und die sichere Aufbewahrung deiner Zugangsdaten verantwortlich. Pro Person ist nur ein Konto zulässig, sofern der Anbieter nicht ausdrücklich etwas anderes erlaubt. Konten dürfen nicht verkauft, übertragen oder zur Manipulation von Rankings verwendet werden.</p></LegalSection>
    <LegalSection title="3. Fair Play und Community"><p>Manipulationen, absichtliche Ergebnisfälschungen, Mehrfachkonten, Belästigung, diskriminierende Inhalte und die Umgehung technischer Schutzmaßnahmen sind untersagt. Bei Verstößen können Matches korrigiert, Turnierzugänge eingeschränkt oder Konten zeitweise bzw. dauerhaft gesperrt werden.</p></LegalSection>
    <LegalSection title="4. Premium-Mitgliedschaft und Zahlung"><p>Premium ist ein kostenpflichtiges, wiederkehrendes Abonnement. Preis, Abrechnungsintervall, enthaltene Leistungen und die Zahlungsbedingungen werden im Stripe-Checkout unmittelbar vor dem Abschluss angezeigt. Die Freischaltung erfolgt nach erfolgreicher Zahlungsbestätigung. Einzelne Vorteile können sich ändern, sofern dies für Nutzer zumutbar ist und der Kern der Leistung erhalten bleibt.</p></LegalSection>
    <LegalSection title="5. Laufzeit und Kündigung"><p>Informationen zur Laufzeit, Abrechnung und Kündigung findest du jederzeit auf der Seite „Premium kündigen“. Eine Kündigung beendet die Verlängerung zum Ende des jeweils aktuellen Abrechnungszeitraums, sofern im Checkout oder gesetzlich nichts anderes bestimmt ist. Gesetzliche Widerrufs- und Kündigungsrechte bleiben unberührt.</p></LegalSection>
    <LegalSection title="6. Verfügbarkeit und Änderungen"><p>Wir bemühen uns um eine hohe Verfügbarkeit, können den Dienst jedoch für Wartung, Sicherheit oder Weiterentwicklung zeitweise einschränken. Ein bestimmtes Matchmaking-Ergebnis, Ranking oder Turnierplatz wird nicht geschuldet.</p></LegalSection>
    <LegalSection title="7. Haftung"><p>Es gelten die gesetzlichen Haftungsregeln. Für Vorsatz, grobe Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie zwingende gesetzliche Ansprüche haften wir unbeschränkt. Im Übrigen ist die Haftung im gesetzlich zulässigen Umfang beschränkt.</p></LegalSection>
    <LegalSection title="8. Änderungen dieser Bedingungen"><p>Bei sachlichem Grund können diese Bedingungen für die Zukunft angepasst werden. Über wesentliche Änderungen informieren wir angemessen; zwingende Rechte der Nutzer bleiben bestehen.</p></LegalSection>
  </LegalPageShell>;
}
