import { LegalPageShell, LegalSection } from '@/components/legal-page-shell';

export default function TermsPage() {
  return <LegalPageShell eyebrow="Nutzungsbedingungen" title="Allgemeine Geschäftsbedingungen" intro="Regeln für die Nutzung der RankedDarts-Plattform und der optionalen Premium-Mitgliedschaft.">
    <LegalSection title="1. Geltungsbereich"><p>Diese Bedingungen regeln die Nutzung von RankedDarts zwischen Arthur Berent als Anbieter und den Nutzern. Für einzelne Turniere gelten ergänzend die Turnierregeln sowie die jeweils auf der Turnierseite genannten Bedingungen.</p></LegalSection>
    <LegalSection title="2. Teilnahme und Nutzerkonto"><p>Die Plattform richtet sich ausschließlich an Personen ab 18 Jahren. Du bist für die Richtigkeit deiner Angaben und die sichere Aufbewahrung deiner Zugangsdaten verantwortlich. Pro Person ist nur ein Konto zulässig, sofern der Anbieter nicht ausdrücklich etwas anderes erlaubt. Konten dürfen nicht verkauft, übertragen oder zur Manipulation von Rankings verwendet werden.</p></LegalSection>
    <LegalSection title="3. Fair Play und Community"><p>Manipulationen, absichtliche Ergebnisfälschungen, Mehrfachkonten, Belästigung, diskriminierende Inhalte und die Umgehung technischer Schutzmaßnahmen sind untersagt. Bei Verstößen können Matches korrigiert, Turnierzugänge eingeschränkt oder Konten zeitweise bzw. dauerhaft gesperrt werden.</p></LegalSection>
    <LegalSection title="4. Premium-Mitgliedschaft und Zahlung"><p>Premium ist ein kostenpflichtiges, wiederkehrendes Abonnement für 4,99 € pro Abrechnungszeitraum. Es umfasst unbegrenzte Spiele und den Zugang zu als Premium gekennzeichneten Turnieren. Gemäß § 19 UStG wird keine Umsatzsteuer berechnet. Das Abrechnungsintervall und die Zahlungsbedingungen werden im Stripe-Checkout unmittelbar vor dem Abschluss angezeigt. Die Freischaltung erfolgt nach erfolgreicher Zahlungsbestätigung.</p></LegalSection>
    <LegalSection title="5. Laufzeit und Kündigung"><p>Informationen zur Laufzeit, Abrechnung und Kündigung findest du jederzeit auf der Seite „Premium kündigen“. Eine Kündigung beendet die Verlängerung zum Ende des jeweils aktuellen Abrechnungszeitraums, sofern im Checkout oder gesetzlich nichts anderes bestimmt ist. Gesetzliche Widerrufs- und Kündigungsrechte bleiben unberührt.</p></LegalSection>
    <LegalSection title="6. Preisgelder und Auszahlungen"><p>Season 01 läuft bis zum 01.11.2026. Sofern auf der Plattform oder in einer Saisonankündigung ein Preisgeld für die Leaderboard-Platzierung zugesagt wird, erfolgt die Auszahlung nach Ende der jeweiligen Season spätestens innerhalb von 30 Tagen. Die Auszahlung erfolgt – je nach Verfügbarkeit und vorheriger Auswahl – per Banküberweisung oder PayPal. Voraussetzung ist, dass die Platzierung abschließend festgestellt wurde, keine offene Fair-Play- oder Identitätsprüfung besteht und die für die Auszahlung erforderlichen Zahlungsdaten vollständig und korrekt vorliegen. Bei fehlenden oder fehlerhaften Daten beginnt die Frist nach deren Nachreichung erneut. Gesetzliche Ansprüche bleiben unberührt.</p></LegalSection>
    <LegalSection title="7. Verfügbarkeit und Änderungen"><p>Wir bemühen uns um eine hohe Verfügbarkeit, können den Dienst jedoch für Wartung, Sicherheit oder Weiterentwicklung zeitweise einschränken. Ein bestimmtes Matchmaking-Ergebnis, Ranking oder Turnierplatz wird nicht geschuldet.</p></LegalSection>
    <LegalSection title="8. Haftung"><p>Es gelten die gesetzlichen Haftungsregeln. Für Vorsatz, grobe Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie zwingende gesetzliche Ansprüche haften wir unbeschränkt. Im Übrigen ist die Haftung im gesetzlich zulässigen Umfang beschränkt.</p></LegalSection>
    <LegalSection title="9. Änderungen dieser Bedingungen"><p>Bei sachlichem Grund können diese Bedingungen für die Zukunft angepasst werden. Über wesentliche Änderungen informieren wir angemessen; zwingende Rechte der Nutzer bleiben bestehen.</p></LegalSection>
  </LegalPageShell>;
}
