import Link from 'next/link';
import { ArrowUpRight, BadgeCheck, CalendarClock, CircleHelp, CreditCard } from 'lucide-react';
import { LegalPageShell, LegalSection } from '@/components/legal-page-shell';

export default function PremiumCancellationPage() {
  return <LegalPageShell eyebrow="Premium · Vertrag & Kündigung" title="Premium kündigen" intro="Hier findest du die wichtigsten Informationen zu Abrechnung, Laufzeit und dem Kündigungsweg für RankedDarts Premium.">
    <div className="rounded-3xl border border-emerald-300/20 bg-emerald-400/[0.08] p-6 sm:p-7"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-emerald-300 text-black"><BadgeCheck className="h-5 w-5" /></div><div><h2 className="text-xl font-black text-white">Kündigung einfach anfordern</h2><p className="mt-2 leading-7 text-emerald-50/80">Öffne ein Support-Ticket mit der Kategorie „Zahlung & Premium“ und dem Betreff „Premium kündigen“. Nenne dabei den Nutzernamen deines Accounts. Wir bestätigen dir den Eingang und den Beendigungszeitpunkt in Textform.</p><Link href="/support" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-4 py-3 text-sm font-black text-black transition hover:bg-emerald-200">Kündigung im Support anfordern <ArrowUpRight className="h-4 w-4" /></Link></div></div></div>
    <LegalSection title="Abrechnung und Laufzeit"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><CreditCard className="h-5 w-5 text-amber-200" /><p className="mt-3 font-black text-white">Preis vor Abschluss</p><p className="mt-1 text-sm text-zinc-400">Preis, Zahlungsart und Abrechnungsintervall werden im Stripe-Checkout klar angezeigt, bevor du zahlungspflichtig abschließt.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><CalendarClock className="h-5 w-5 text-cyan-300" /><p className="mt-3 font-black text-white">Ende der Verlängerung</p><p className="mt-1 text-sm text-zinc-400">Nach einer Kündigung läuft Premium grundsätzlich bis zum Ende des bereits bezahlten Abrechnungszeitraums weiter, soweit im Checkout nichts Abweichendes steht.</p></div></div></LegalSection>
    <LegalSection title="Was passiert nach der Kündigung?"><p>Bis zum Ende des laufenden Zeitraums bleiben die Premium-Vorteile aktiv. Danach wird dein Konto als kostenloses Konto weitergeführt; dein Account, deine Matchhistorie und deine Profildaten bleiben erhalten, sofern du keine Löschung beantragst.</p></LegalSection>
    <LegalSection title="Hilfe bei Zahlungsthemen"><p>Bei einer unbekannten Abbuchung, einer fehlerhaften Zahlung oder Problemen mit dem Kündigungsweg nutze ebenfalls den Support. Halte keinen vollständigen Karten- oder Zahlungsdaten im Ticket fest.</p><Link href="/support" className="inline-flex items-center gap-2 font-black text-emerald-200 transition hover:text-emerald-100">Premium-Support öffnen <CircleHelp className="h-4 w-4" /></Link></LegalSection>
    <LegalSection title="Wichtiger Hinweis"><p>Der direkte Kündigungsweg und die Bestätigung müssen vor dem produktiven Betrieb rechtlich geprüft und technisch final eingerichtet werden. Insbesondere bei Verbraucherverträgen können gesetzliche Anforderungen an eine unmittelbar erreichbare Online-Kündigung bestehen.</p></LegalSection>
  </LegalPageShell>;
}
