import { LegalPageShell, LegalSection } from '@/components/legal-page-shell';

export default function PrivacyPage() {
  return <LegalPageShell eyebrow="Datenschutz" title="Datenschutzerklärung" intro="Informationen zur Verarbeitung personenbezogener Daten bei der Nutzung von RankedDarts.">
    <LegalSection title="1. Verantwortliche Stelle"><p>Verantwortlich für die Datenverarbeitung ist Arthur Berent, Milanstraße 16, 14612 Falkensee, E-Mail: <a className="font-bold text-emerald-200 hover:text-emerald-100" href="mailto:support@rankeddarts.de">support@rankeddarts.de</a>.</p></LegalSection>
    <LegalSection title="2. Welche Daten wir verarbeiten"><p>Bei der Registrierung und Nutzung verarbeiten wir insbesondere Accountdaten (E-Mail-Adresse, Nutzername, Authentifizierungs-ID), Profil- und Spielstatistiken, Turnier- und Matchdaten, Support-Nachrichten sowie – sofern aktiviert – Daten zur Telefonverifizierung. Technische Protokolldaten können bei der Bereitstellung der Website anfallen.</p></LegalSection>
    <LegalSection title="3. Zwecke und Rechtsgrundlagen"><p>Die Datenverarbeitung dient der Bereitstellung des Nutzerkontos, Matchmakings, der Turniere, Kommunikation, Betrugs- und Missbrauchsprävention sowie der Zahlungsabwicklung. Rechtsgrundlagen können Art. 6 Abs. 1 lit. b DSGVO (Vertrag), lit. c (rechtliche Pflicht), lit. f (berechtigte Interessen) und – sofern erforderlich – lit. a (Einwilligung) sein.</p></LegalSection>
    <LegalSection title="4. Eingesetzte Dienstleister"><p><strong>Supabase</strong> wird für Authentifizierung und Datenbankfunktionen eingesetzt. <strong>Stripe</strong> verarbeitet Zahlungsdaten für Premium-Abonnements. <strong>Vercel</strong> stellt die Website technisch bereit und kann hierfür technische Protokolldaten verarbeiten. <strong>STRATO</strong> wird für die E-Mail-Kommunikation über support@rankeddarts.de eingesetzt. Es gelten zusätzlich die Datenschutzhinweise der jeweiligen Dienstleister.</p></LegalSection>
    <LegalSection title="5. Speicherdauer"><p>Kontodaten, Match- und Turnierdaten speichern wir grundsätzlich für die Dauer des Nutzerkontos. Support-Nachrichten werden gelöscht oder anonymisiert, sobald sie für die Bearbeitung nicht mehr erforderlich sind. Zahlungs- und Abrechnungsdaten können aufgrund gesetzlicher Aufbewahrungspflichten länger gespeichert werden.</p></LegalSection>
    <LegalSection title="6. Deine Rechte"><p>Du hast – soweit die Voraussetzungen vorliegen – das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Erteilte Einwilligungen kannst du mit Wirkung für die Zukunft widerrufen. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p></LegalSection>
    <LegalSection title="7. Kontakt für Datenschutzanfragen"><p>Bitte sende Datenschutzanfragen an <a className="font-bold text-emerald-200 hover:text-emerald-100" href="mailto:support@rankeddarts.de">support@rankeddarts.de</a>.</p></LegalSection>
  </LegalPageShell>;
}
